### ISSUE TITLE
Software package versions

### ISSUE THREAD

**Issue by StasyanOi** [david-svitov/baldgan#1]
Hello, what versions of tensorflow and keras were used for this project?

**Comment by david-svitov** [comment]
keras=2.3.1
matplotlib=3.3.4
numpy=1.19.2
opencv-python=4.5.1.48
keras-contrib=2.0.8 git+https://www.github.com/keras-team/keras-contrib.git
scikit-image=0.17.2

**Comment by StasyanOi** [comment]
@david-svitov thanks!
