### ISSUE TITLE
Having trouble with testing

### ISSUE THREAD

**Issue by jinwoo1225** [david-svitov/baldgan#3]
I have an interest in this project. So I tried to test this code but failed to install opencv-python and keras-contrib. 
Currently having this kind of error message
Enviroment : 
OS : Ubuntu 20.04LTS
Python : 3.9
Conda : MiniConda 4.10
```

Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - opencv-python==4.5.1.48
  - //www.github.com/keras-team/keras-contrib.git

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


```

**Comment by david-svitov** [comment]
Yes, conda has problems with opencv. I usually solve this problem by installing with pip:
```
pip install opencv-python
```

**Comment by jinwoo1225** [comment]
@david-svitov Can I ask which retinaface repository did you used? Link that you provided in readme doesn't worked for me.. 🥲

**Comment by david-svitov** [comment]
@jinwoo1225 Yes, the repository authors did a refactor and some paths have changed. Here's the new path to RetinaFace: https://github.com/deepinsight/insightface/tree/master/detection/retinaface

**Comment by jinwoo1225** [comment]
@david-svitov oh we just implemented our own retinaface using dlib. check this out!
https://github.com/2021-HKNU-CD/HAiR/pull/31
